// Array of local product images (served from public/images)
const imageUrls = [
  "/images/image1.avif",
  "/images/image2.avif",
  "/images/image3.avif",
  "/images/image4.avif",
  "/images/image5.avif",
  "/images/image6.avif",
  "/images/image7.avif",
  "/images/image8.avif",
  "/images/image9.avif",
  "/images/image10.avif",
  "/images/image11.avif",
  "/images/image12.avif",
  "/images/image13.avif",
  "/images/image14.avif",
  "/images/image15.avif",
  "/images/image16.avif",
  "/images/image17.avif",
  "/images/image18.avif",
  "/images/image19.avif",
  "/images/image20.avif",
  "/images/Product1.jpg",
];


function getRandomImages(count: number, baseIndex: number): string[] {
  const images: string[] = [];
  for (let i = 0; i < count; i++) {
    images.push(imageUrls[(baseIndex + i) % imageUrls.length]);
  }
  return images;
}

// Product data for all collections
export const productsData = {
  "regular-tees": [
    {
      id: 1,
      name: "ATTACK ON TITAN SCOUT TEE",
      price: "₹699",
      rating: 4.8,
      reviews: 127,
      badges: ["Bestseller"],
      image: imageUrls[0],
      images: getRandomImages(3, 0),
      description: "Premium Gaming Streetwear",
      highlights: [
        "Premium Cotton Blend",
        "High Quality Print",
        "Regular Fit",
      ],
      colors: ["Black", "White", "Navy"],
      sizes: ["S", "M", "L", "XL", "XXL"],
    },
    {
      id: 2,
      name: "DRAGON BALL Z POWER TEE",
      price: "₹549",
      rating: 4.5,
      reviews: 89,
      badges: [],
      image: imageUrls[1],
      images: getRandomImages(3, 1),
      description: "Premium Gaming Streetwear",
      highlights: [
        "Premium Cotton Blend",
        "High Quality Print",
        "Regular Fit",
      ],
      colors: ["Black", "White", "Navy"],
      sizes: ["S", "M", "L", "XL", "XXL"],
    },
    {
      id: 3,
      name: "ONE PIECE STRAW HAT TEE",
      price: "₹649",
      rating: 4.6,
      reviews: 102,
      badges: ["Limited Edition"],
      image: imageUrls[2],
      images: getRandomImages(3, 2),
      description: "Premium Gaming Streetwear",
      highlights: [
        "Premium Cotton Blend",
        "High Quality Print",
        "Regular Fit",
      ],
      colors: ["Black", "White", "Navy"],
      sizes: ["S", "M", "L", "XL", "XXL"],
    },
    {
      id: 4,
      name: "NARUTO UZUMAKI CLASSIC TEE",
      price: "₹599",
      rating: 4.7,
      reviews: 115,
      badges: [],
      image: imageUrls[3],
      images: getRandomImages(3, 3),
      description: "Premium Gaming Streetwear",
      highlights: [
        "Premium Cotton Blend",
        "High Quality Print",
        "Regular Fit",
      ],
      colors: ["Black", "White", "Navy"],
      sizes: ["S", "M", "L", "XL", "XXL"],
    },
  ],
  "oversized-tees": [
    {
      id: 5,
      name: "GUSION2-MLBB - OVERSIZED TEES",
      price: "₹899",
      rating: 4.9,
      reviews: 142,
      badges: ["Bestseller"],
      image: imageUrls[4],
      images: getRandomImages(3, 4),
      description: "Premium Gaming Streetwear",
      highlights: [
        "Premium Cotton Blend",
        "High Quality Print",
        "Oversized Fit",
      ],
      colors: ["Black", "White", "Navy"],
      sizes: ["S", "M", "L", "XL", "XXL"],
    },
    {
      id: 6,
      name: "GUSION-MLBB - OVERSIZED TEES",
      price: "₹899",
      rating: 4.8,
      reviews: 131,
      badges: [],
      image: imageUrls[5],
      images: getRandomImages(3, 5),
      description: "Premium Gaming Streetwear",
      highlights: [
        "Premium Cotton Blend",
        "High Quality Print",
        "Oversized Fit",
      ],
      colors: ["Black", "White", "Navy"],
      sizes: ["S", "M", "L", "XL", "XXL"],
    },
  ],
  "acid-wash": [
    {
      id: 7,
      name: "CYBER PUNK ACID WASH",
      price: "₹1149",
      rating: 4.7,
      reviews: 98,
      badges: ["Limited Edition"],
      image: imageUrls[6],
      images: getRandomImages(3, 6),
      description: "Vintage Wash Aesthetic",
      highlights: [
        "Acid Wash Finish",
        "Premium Cotton",
        "Retro Style",
      ],
      colors: ["Black", "Purple", "Blue"],
      sizes: ["S", "M", "L", "XL", "XXL"],
    },
    {
      id: 8,
      name: "RETRO GAMING ACID TEE",
      price: "₹999",
      rating: 4.6,
      reviews: 87,
      badges: [],
      image: imageUrls[7],
      images: getRandomImages(3, 7),
      description: "Vintage Wash Aesthetic",
      highlights: [
        "Acid Wash Finish",
        "Premium Cotton",
        "Retro Style",
      ],
      colors: ["Black", "Purple", "Blue"],
      sizes: ["S", "M", "L", "XL", "XXL"],
    },
    {
      id: 9,
      name: "VINTAGE ANIME ACID WASH",
      price: "₹1099",
      rating: 4.8,
      reviews: 112,
      badges: ["Bestseller"],
      image: imageUrls[8],
      images: getRandomImages(3, 8),
      description: "Vintage Wash Aesthetic",
      highlights: [
        "Acid Wash Finish",
        "Premium Cotton",
        "Retro Style",
      ],
      colors: ["Black", "Purple", "Blue"],
      sizes: ["S", "M", "L", "XL", "XXL"],
    },
  ],
  hoodies: [
    {
      id: 10,
      name: "ANIME COZY OVERSIZED HOODIE",
      price: "₹1999",
      rating: 4.9,
      reviews: 156,
      badges: ["Bestseller"],
      image: imageUrls[9],
      images: getRandomImages(3, 9),
      description: "Ultra cozy & premium layering",
      highlights: [
        "Premium Fleece",
        "Oversized Fit",
        "High Quality Print",
      ],
      colors: ["Black", "Gray", "Navy"],
      sizes: ["S", "M", "L", "XL", "XXL"],
    },
    {
      id: 11,
      name: "MLBB SQUAD HOODIE",
      price: "₹1799",
      rating: 4.7,
      reviews: 134,
      badges: ["Limited Edition"],
      image: imageUrls[10],
      images: getRandomImages(3, 10),
      description: "Ultra cozy & premium layering",
      highlights: [
        "Premium Fleece",
        "Oversized Fit",
        "High Quality Print",
      ],
      colors: ["Black", "Gray", "Navy"],
      sizes: ["S", "M", "L", "XL", "XXL"],
    },
    {
      id: 12,
      name: "PRO GAMER OVERSIZED HOODIE",
      price: "₹1899",
      rating: 4.8,
      reviews: 143,
      badges: [],
      image: imageUrls[11],
      images: getRandomImages(3, 11),
      description: "Ultra cozy & premium layering",
      highlights: [
        "Premium Fleece",
        "Oversized Fit",
        "High Quality Print",
      ],
      colors: ["Black", "Gray", "Navy"],
      sizes: ["S", "M", "L", "XL", "XXL"],
    },
  ],
  sweatshirts: [
    {
      id: 13,
      name: "RETRO PIXEL ART SWEATSHIRT",
      price: "₹1249",
      rating: 4.8,
      reviews: 127,
      badges: ["Bestseller"],
      image: imageUrls[12],
      images: getRandomImages(3, 12),
      description: "Clean look for chilly days",
      highlights: [
        "Premium Cotton Blend",
        "Comfortable Fit",
        "Vintage Design",
      ],
      colors: ["Black", "Navy", "White"],
      sizes: ["S", "M", "L", "XL", "XXL"],
    },
    {
      id: 14,
      name: "MINIMALIST GAMING SWEATSHIRT",
      price: "₹2999",
      rating: 4.9,
      reviews: 168,
      badges: ["Limited Edition"],
      image: imageUrls[13],
      images: getRandomImages(3, 13),
      description: "Clean look for chilly days",
      highlights: [
        "Premium Cotton Blend",
        "Comfortable Fit",
        "Minimalist Design",
      ],
      colors: ["Black", "Navy", "White"],
      sizes: ["S", "M", "L", "XL", "XXL"],
    },
    {
      id: 15,
      name: "GAMER CREW SWEATSHIRT",
      price: "₹1399",
      rating: 4.7,
      reviews: 119,
      badges: [],
      image: imageUrls[14],
      images: getRandomImages(3, 14),
      description: "Clean look for chilly days",
      highlights: [
        "Premium Cotton Blend",
        "Comfortable Fit",
        "Gamer Design",
      ],
      colors: ["Black", "Navy", "White"],
      sizes: ["S", "M", "L", "XL", "XXL"],
    },
    {
      id: 16,
      name: "CLASSIC ANIME SWEATSHIRT",
      price: "₹1299",
      rating: 4.8,
      reviews: 135,
      badges: ["Bestseller"],
      image: imageUrls[15],
      images: getRandomImages(3, 15),
      description: "Clean look for chilly days",
      highlights: [
        "Premium Cotton Blend",
        "Comfortable Fit",
        "Anime Design",
      ],
      colors: ["Black", "Navy", "White"],
      sizes: ["S", "M", "L", "XL", "XXL"],
    },
  ],
};

export const getProductsByCollection = (handle: string) => {
  return productsData[handle as keyof typeof productsData] || [];
};

export const getProductById = (handle: string, id: number) => {
  const products = getProductsByCollection(handle);
  return products.find((p) => p.id === id);
};
